---
version: '3'

services:
  drupal:
    build: ./
    image: geerlingguy/drupal:latest
    container_name: drupal
    environment:
      DRUPAL_DATABASE_HOST: drupal-mysql
    ports:
      - "80:80"
    restart: always
    # Uncomment the volumes line and set to the local path of your Drupal
    # installation, if you need to work with a local codebase.
    # volumes:
    #   - ~/Sites/drupal-container:/var/www/html:rw,delegated

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
