---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    build_x86: true
    build_arm: true

  tasks:
    - name: Build the x86 Docker image from the main Dockerfile.
      docker_image:
        path: ./
        nocache: true
        name: geerlingguy/drupal
        tag: latest
        force: true
      when: build_x86

    - name: Copy entrypoint into arm32v7 folder temporarily.
      copy:
        src: docker-entrypoint.sh
        dest: arm32v7/docker-entrypoint.sh
        mode: 0755

    - name: Build the arm32v7 Docker image from the arm Dockerfile.
      docker_image:
        path: ./arm32v7/
        nocache: true
        name: geerlingguy/drupal
        tag: latest-arm32v7
        force: true
      when: build_arm

    - name: Remove temporary entrypoint file.
      file:
        path: arm32v7/docker-entrypoint.sh
        state: absent
